export const MICROSERVICE_NAMES = {
  USERS: 'USERS_SERVICE',
  PRODUCT: 'PRODUCT_SERVICE',
  INVENTORY: 'INVENTORY_SERVICE',
  ORDER: 'ORDER_SERVICE',
  PAYMENT: 'PAYMENT_SERVICE',
  SHIPPING: 'SHIPPING_SERVICE',
  AUDIT: 'AUDIT_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
};
